### ISSUE TITLE
Losing data after reboot

### ISSUE THREAD

**Issue by Bluhme1** [sveinse/zaptec#28]
Hello

I am using the sensor.XXXXXX_session_total_charge to monitor my actual charge session. I am also using it for calculating daily, weekly, monthly and yearly use by loading it as a source entity to the Utility Meter Helper.
After reboot af HA this sensor turn "unknown" and when the Utility Meter starts calculating it misses the first reading as it subtracts the new reading from the the old - but there's is no old one as it is marked unknown until it gets the first reading.
 I have looked in you code and cannot find the key "total_charge_power_session" in the API response

/Lars

**Comment by sveinse** [comment]
The "total_charge_power_session" is not a part of data delivered by the Zaptec Cloud API response (URL `chargers/<uid>`). Instead it is delivered by the state data (URL `chargers/<uid>/state`). However the cloud often omits this particular key "total_charge_power_session" (which is named `stateId = 553` or `TotalChargePowerSession` in Zaptec systems). This unfortunately leaves it as unknown after startup because, well, the value is unknown. When charging, the cloud will start to update these states and thus it gets a value in HA.

I'm not aware of any methods to actively request that value for the missing state.

**Comment by Bluhme1** [comment]
You are right. Sometimes the API provides data for this sensor - sometimes it doesn't 
I have written a "trigger-template" that only lets the sensor update when it it not "unknown". If "the total_power_charge_session" is unknown it is ignored and the value sets to 0 (zero)

 - trigger:
     - platform: state
       entity_id: sensor.XXXXXXXX_session_total_charge
       not_to:
         - "unavailable"
         - "unknown"
         - "none"
   sensor:
    - name:         "XXXXXXX_session_total_charge NOW"
      state:        "{{ states('sensor.XXXXX_session_total_charge') | float(0) }}"
      state_class:  "total_increasing"

I am closing this issue
